version:  "3.7"
services:
  php:
    container_name: ccat-php
    build:
      context: ./docker/php
      args:
        - UID=${UID}
        - GID=${GID}
    ports:
      - "8081:8081"
    volumes:
      - ./:/var/www/ccat-php
    networks:
      - cheshire-cat_default

networks:
  cheshire-cat_default:
    external: true